namespace TUTASAPrototipo.Almacenes
{
    public enum ProvinciaEnum
    {
        BuenosAires,
        Catamarca,
        Chaco,
        Chubut,
        CABA,
        Cordoba,
        Corrientes,
        EntreRios,
        Formosa,
        Jujuy,
        LaPampa,
        LaRioja,
        Mendoza,
        Misiones,
        Neuquen,
        RioNegro,
        Salta,
        SanJuan,
        SanLuis,
        SantaCruz,
        SantaFe,
        SantiagoDelEstero,
        TierraDelFuego,
        Tucuman,
    }
}
